### PR TITLE
Feature/add GitHub ci

### PR DESCRIPTION
**Pull request by Manuthor**
- [x] replace gitlab CI with github CI
- [x] make sure native libs are included in published package
- [x] generated bindings are commited (for potential windows users) and still regenerated by `get_native_libraries.py`
- [x] check package import from internet
- [x] make sure `get_native_libraries.py` does not fetch package outside of github 
- [x] support of covercrypt 9 

Waiting for CoverCrypt pipeline to be finished

### CODE REVIEW

**Comment by ThibaudDauce** [comment]
Why `generated_bindings.dart` are inside Git for Windows? They should be downloaded from `packages` alongside the binaries I think.

**Comment by Manuthor** [comment]
About the `generated_bindings.dart`, I am afraid than Windows users not being able to generate them by themselves (unless they install the llvm binaries)

**Comment by ThibaudDauce** [comment]
> About the `generated_bindings.dart`, I am afraid than Windows users not being able to generate them by themselves (unless they install the llvm binaries)

Hum… Why? `generated_bindings.dart` are generated  from the `.h` with a Flutter script https://pub.dev/packages/ffigen. I don't think it requires llvm?

**Comment by ThibaudDauce** [comment]
> > About the `generated_bindings.dart`, I am afraid than Windows users not being able to generate them by themselves (unless they install the llvm binaries)
> 
> Hum… Why? `generated_bindings.dart` are generated from the `.h` with a Flutter script https://pub.dev/packages/ffigen. I don't think it requires llvm?

If it's really a problem for Windows users, I think `cloudproof_flutter` should publish these to `packages.cosmian.com` and we should download `generated_bindings.dart` from `packages.cosmian.com` alongside the binaries

**Comment by Manuthor** [comment]
> Hum… Why? generated_bindings.dart are generated from the .h with a Flutter script https://pub.dev/packages/ffigen. I don't think it requires llvm?

this is the cas for ubuntu and macos (llvm is used by ffigen)

**Comment by Manuthor** [comment]
> If it's really a problem for Windows users, I think cloudproof_flutter should publish these to packages.cosmian.com and we should download generated_bindings.dart from packages.cosmian.com alongside the binaries

we could do this

**Pull request merged**
